[project]
name = "goblin-messenger"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "sqlmodel>=0.0.31",
    "typer>=0.21.1",
<<<<<<< HEAD
    "psutil>=6.1.1",
    "httpx>=0.28.1",
=======
>>>>>>> main
]
